### ISSUE TITLE
[BUG] Sound engine crash with invalid generators (Segmentation Fault)

### ISSUE THREAD

**Issue by spessasus** [davy7125/polyphone#195] opened 2024-06-12 17:13 UTC
## The issue:
Polyphone crashes when out of limits generators are attempted to be played. (Pan generator here.)
The Pan generators are set to -100 and 100 respectively.
## Expected behavior
It should not crash, even if it's invalid. One of the four solutions:
1. Discard the generators like fluidsynth [code](https://github.com/FluidSynth/fluidsynth/blob/f9bde410216766c1117cd07b349740e9804773ca/src/sfloader/fluid_sffile.c#L1459)
2. Clamp the generator values at note on time like SpessaSynth [code](https://github.com/spessasus/SpessaSynth/blob/d99ac04913b51652f3d7dd8f01e772cc103abd59/src/spessasynth_lib/soundfont/chunk/generators.js#L153)
3. Automatically clamp the generators (at load time)
4. Remove the generators (set to the default value)
## Steps to reproduce:
1. Download the attached soundfont
2. Open it in Polyphone
3. Try to play a key
5. Polyphone Crashes
## OS
Happens both on Windows (10) and Linux (Arch) with the latest version installed.

## Soundfont
[PolyphoneCrash.zip](https://github.com/user-attachments/files/15808565/PolyphoneCrash.zip)

### Logs (Linux):
```zsh
spessasus@spessasus-gaming ~> polyphone
fish: Job 1, 'polyphone' terminated by signal SIGSEGV (Address boundary error)
spessasus@spessasus-gaming ~ [SIGSEGV]> 

```

**Comment by davy7125** [comment] 2024-07-28 15:23
This might have already been solved since I cannot reproduce the bug with the latest sources.
I'm closing the ticket

**Closed by davy7125** 2024-07-28 15:23 UTC
