### ISSUE TITLE
DLS format support

### ISSUE THREAD

**Issue by kmoon2437** [davy7125/polyphone#196] opened 2024-06-28 17:05 UTC
http://www.polyphone-soundfonts.com/fr/forum/feature-requests/111-dls-format-support#370

**Comment by davy7125** [comment] 2024-07-20 13:52
Outch 7 years ago already... This is still in the list.
I have been delayed with the website but the development will continue now.
Let's keep ticket 8 open
Duplicate of #8

**Closed by davy7125** 2024-07-20 13:52 UTC
